redis:
  extends:
    file: docker-compose-base.yml
    service: redis

server:
  extends:
    file: docker-compose-base.yml
    service: server
  links:
    - redis:db

worker:
  extends:
    file: docker-compose-base.yml
    service: worker
  links:
    - redis:db
  command: ./script/worker  --loglevel=info

dashboard:
  extends:
    file: docker-compose-base.yml
    service: dashboard
  links:
    - redis:db
  env_file:
    - .env
    - .env.production
  command: ./script/dashboard --auth_provider=flower.views.auth.GithubLoginHandler --auth=maingithubemail@example.com
